version: "3"

services:
  
  api-demo-node:
    image: node
    container_name: api-demo-node
    networks: 
      - demo-compose
    volumes:
      - ./IMS-Service:/home/node/app
    ports:
      - 80:80
    depends_on: 
      - database-demo-mongodb
    working_dir: /home/node/app
    command: ["node", "index.js"]

  database-demo-mongodb:
    image: mongo
    container_name: database-demo-mongodb
    networks: 
      - demo-compose
    volumes:
      - ./Mongodb/ims:/backup
      - ./Mongodb/restore:/docker-entrypoint-initdb.d 
      - data-ims:/data/db
    expose: 
      - "27017"

  admin-mongo-express:
    image: mongo-express
    container_name: admin-mongo-express
    environment: 
      - ME_CONFIG_MONGODB_SERVER=database-demo-mongodb
    networks: 
      - demo-compose
    ports:
      - 8080:8081
    depends_on: 
      - database-demo-mongodb
    expose:
      - "8081"

networks: 
  demo-compose:

volumes:
  data-ims: